\NeedsTeXFormat{LaTeX2e}
\ProvidesExplClass{test}{2022/12/26}{v1.0}{Personal Template for Super SASS}


% + %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 装载其他类或宏包
\LoadClass[a4paper,12pt]{article}
\RequirePackage{ctex}
\RequirePackage{geometry}
% - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\setlength\parindent{2em}
\setmainfont{Times~New~Roman}
%\setmonofont{Courier New}
\setsansfont{Arial}

% \NeedsTeXFormat{LaTeX2e}
% \ProvidesClass{test}[2022/12/26 v1.0 Personal Template for Super SASS]

% \LoadClass[a4paper,12pt]{article}
% \RequirePackage{ctex}


% \setlength\parindent{2em}
% \setmainfont{Times New Roman}
% %\setmonofont{Courier New}
% \setsansfont{Arial}